config/routes.rb
Tienda::Application.routes.draw do
  get "home/index"

  resources :productos

   root :to => "Productos#index"

end

app/models/producto.rb
class Producto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.xml
  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.xml
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.xml
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.xml
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to(@producto, :notice => 'Producto was successfully created.') }
        format.xml  { render :xml => @producto, :status => :created, :location => @producto }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @producto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.xml
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to(@producto, :notice => 'Producto was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @producto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.xml
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to(productos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tienda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.text_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar"%>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editar producto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @producto %> |
<%= link_to 'Regresar', productos_path %>

app/views/productos/index.html.erb
<h1>Lista de productos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Precio</th>
    <th>Descripción</th>
    <th>Cantidad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productos.each do |producto| %>
  <tr>
    <td><%= producto.nombre %></td>
    <td><%= producto.precio %></td>
    <td><%= producto.descripcion %></td>
    <td><%= producto.cantidad %></td>
    <td><%= link_to 'Mostrar', producto %></td>
    <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
    <td><%= link_to 'Borrar', producto, :confirm => '¿Está seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Agregar Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>Nuevo producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @producto.nombre %>
</p>

<p>
  <b>Precio:</b>
  <%= @producto.precio %>
</p>

<p>
  <b>Descripción:</b>
  <%= @producto.descripcion %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @producto.cantidad %>
</p>


<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Regresar', productos_path %>